In [1]:
from google.cloud import bigquery
import pandas as pd

In [2]:
client = bigquery.Client(project='subugoe-collaborative')

In [8]:
filter_umg = client.query(f"""
                           SELECT inst.doi, address_full
                           FROM `subugoe-collaborative.openbib.kb_a_addr_inst` AS inst
                           JOIN `subugoe-collaborative.openbib.kb_inst_lookup` AS kb_inst
                               ON inst.inst_id_top = kb_inst.inst_id
                           WHERE kb_inst.ror = 'https://ror.org/01y9bpm73' 
                          """).to_dataframe()

In [10]:
filter_umg.head()

,doi,address_full
0,10.1057/gpp.1998.13,University of Goettingen
1,10.1016/b978-012369542-0/50009-x,"Institute for Medical Microbiology, University..."
2,10.1007/978-3-540-74984-4_4,"Institute for Informatics, University of Götti..."
3,10.1111/j.1365-2184.2010.00690.x,"Department of Clinical Chemistry, University M..."
4,10.2139/ssrn.903048,University of Goettingen (Göttingen) - School ...

In [18]:
df = filter_umg.copy()

In [19]:
df['institution'] = 'Universität Göttingen'

In [20]:
# https://github.com/naustica/affiliation_mapping/blob/main/affiliation_mapping.py
# Universitätsmedizin
med = ['umg', 'oncol', 'med', 'cardiol', 'clin', 'pneumol', 'klini',
       'multiscale bioimaging', 'cardiovasc',
       'urol', 'gastroenter', 'surg', 'physio', 'psychia',
       'dent', 'pathol', 'radiol', 'adv.* imag', 'heilkunde',
       '\w*klin', 'robert[-\s]koch', 'hosp', 'otorhinolaryngol', 'otolaryngol',
       'immu', 'pharma[ck]ol', 'ophthal', 'rheuma']

In [24]:
# https://ror.org/021ft0n22 UMG

In [21]:
df.loc[df['address_full'].str.contains('|'.join(med), case=False, regex=True), ['institution']] = 'Universitätsmedizin Göttingen'

In [22]:
df

,doi,address_full,institution
0,10.1057/gpp.1998.13,University of Goettingen,Universität Göttingen
1,10.1016/b978-012369542-0/50009-x,"Institute for Medical Microbiology, University...",Universitätsmedizin Göttingen
2,10.1007/978-3-540-74984-4_4,"Institute for Informatics, University of Götti...",Universität Göttingen
3,10.1111/j.1365-2184.2010.00690.x,"Department of Clinical Chemistry, University M...",Universitätsmedizin Göttingen
4,10.2139/ssrn.903048,University of Goettingen (Göttingen) - School ...,Universität Göttingen
...,...,...,...
144659,10.36198/9783838537719,Universität Göttingen,Universität Göttingen
144660,10.1007/978-3-662-28819-1_14,Universität Göttingen,Universität Göttingen
144661,10.1007/978-3-476-04474-7_23,Universität Göttingen,Universität Göttingen
144662,10.1007/978-3-662-36809-1_1,Universität Göttingen,Universität Göttingen
144663,10.36311/2318-0501.2022.v10n1.p91,Universität Göttingen,Universität Göttingen

In [23]:
df[df.institution == 'Universität Göttingen'].address_full.unique().tolist()

['University of Goettingen',
 'Institute for Informatics, University of Göttingen, Göttingen, Germany#TAB#',
 'University of Goettingen (Göttingen) - School of Law, Economics, Social Sciences',
 'Gesellschaft für wissenschaftliche Datenverarbeitung mbH Göttingen, Deutschland',
 'Universität Göttingen, Göttingen, Deutschland',
 'Georg-August University Goettingen, Institute of Animal Breeding and Genetics, Tropical Animal Production, Kellnerweg 6, 37077 Goettingen, Germany',
 'Gesellschaft für wissenschaftliche Datenverarbeitung mbh Göttingen, Deutschalnd',
 'UNIVERSITAET GOETTINGEN',
 'Universitaets-Sternwarte Goettingen, Germany',
 'der Georg-August-Universität zu Göttingen vorgelegt',
 'Zentralverwaltung, Universität Göttingen, Göttingen, Deutschland',
 'Department of Economics , University of Göttingen , Platz der Göttinger Sieben 3, 37073, Göttingen, Germany',
 'Institut für Metallphysik, Universität Göttingen, Germany',
 'Georg August University, Göttingen, Germany',
 'Albrecht-von-Haller Institut für Pflanzenwissenschaften, Universität Göttingen, Germany',
 'Ausgeführt im physikalisch-chemischen Institute der Universität Göttingen, Deutschland',
 'Universität Göttingen, Göttingen',
 'Georg‐August‐Universität, Göttingen Germany',
 'Institut für Anorganische Chemie der Universität, Tammannstrasse 4, D-3400 Göttingen F.R.G.',
 'Chairgroup for Forest and Nature Conservation Policy, University of Göttingen, Büsgenweg 3, 37077 Göttingen, Germany',
 'Department of Prosthodontics, Georg-August- University Goettingen, D-37075 Goettingen, Germany',
 'II. Physikalisches Institut, Georg-August-Universität Göttingen, Göttingen, Deutschland',
 'Georg-August Universität Göttingen',
 'Center of Anatomy, Department of Neuroanatomy, University of Goettingen, Goettingen, Germany.',
 'Institute of Organic and Biomolecular Chemistry , University of Göttingen , Tammannstrasse 2 , 37077 Göttingen , Germany.',
 'Geochemisches Institut der Universität, 34 Göttingen, Goldschmidtstrasse 1, Germany',
 'Universität Göttingen, Deutschland',
 'Georg-Elias-Müller-Institute of Psychology, University of Goettingen, Goßlerstr. 14, D-37073 Goettingen, Germany',
 'Institut für Mathematische Statistik, Universität Göttingen, Göttingen, West Germany',
 'Mathematisches Institut der Georg-August-Universität, Göttingen, Bundesrepublik Deutschland',
 'Institut für Organische Chemie, Georg-August-Universität Göttingen, Göttingen,',
 'Univ.-Sternwarte, Göttingen, Germany',
 'University of Goettingen, Wirtschaftswissenschaftliche Fakultaet, Platz der Goettinger Sieben 3, 37073 Goettingen, Germany',
 'Drittes Physikalisches Institut, Georg-August-Universität, Bürgerstrasse 42-44, 37073 Göttingen, Germany',
 'Institut für Anthropologie der Georg August-Universität, Bürgerstr. 50, 3400, Göttingen, Germany',
 'Universitäts-Sternwarte, Geismarlandstr.11, D-3400, Göttingen, West Germany',
 'Anorganisch-Chemisches Institut, Universität Göttingen, Göttingen, Federal Republic of Germany',
 'Mineralogisch-Petrologisches Institut der Georg-August Universität, Göttingen, Germany',
 'Institute of Inorganic Chemistry, University of Göttingen, Göttingen, Germany',
 'Albrecht-von-Haller Institute of Plant Sciences, Department of Systematics, Biodiversity and Evolution of Plants, Georg-August-University of Göttingen, Göttingen, Germany',
 'Fachbereich Wirtschaftswissenschaften, Georg-August-Universität Göttingen, Göttingen, Deutschland',
 'Institut für Mikrobiologie, Georg-August-Universität zu Göttingen, Germany.',
 'Georg-August-Universität Göttingen, Institut für Mikrobiologie, Grisebachstr. 8, D-37077 Göttingen, Germany',
 'University of Goettingen Institute of Materials Physics, , Friedrich-Hund-Platz 1, Goettingen 37077, Germany',
 'University of Göttingen, Institut für Materialphysik, Friedrich-Hund-Platz 1, D-37077 Göttingen, Germany',
 'Institut für Agrikulturchemie der Georg August-Universität, Gottingen, Germany',
 'Institut für Demokratieforschung, Georg-August-Universität Göttingen, Göttingen, Deutschland',
 'Institut für Physikalische Chemie Universität Göttingen (Germany)',
 'Department of Structural Geology and Geodynamics, Geoscience Centre, University of Göttingen, Goldschmidtstrasse 3, 37077 Göttingen, Germany',
 'Institute of Microbiology and Genetics, Georg August University Göttingen, Göttingen, Germany',
 'Mathematisches Institut der Georg-August Universität',
 'Faculty of Physics Institute of Theoretical Physics, Georg-August University, Göttingen, Göttingen, Germany',
 'Institute for Crop and Animal Production in the Tropics, Georg-August-University, Grisebachstr. 6, D-37077, Göttingen, Germany',
 'Chair for Economic Policy and SME Research, Economics Department, University of Göttingen, Platz der Göttinger Sieben 3, D-37073, Göttingen',
 'II Institute of Physics, University of Göttingen, D-37073 Göttingen, Germany',
 'Universität Gottingen, Deutschland',
 'Department of Physics, University of Göttingen, Friedrich-Hund-Platz 1, 37077 Göttingen, Germany',
 'Institut für Numerische und Angewandte Mathematik, Universität Göttingen, Lotzestr. 16–18, D3400, Göttingen, Germany',
 'Institut für Organische Chemie der Georg-August Universität, Göttingen, Germany',
 'Institut für Mikrobiologie, Georg-August-Universität Göttingen, Göttingen, Germany',
 'Department of Biochemistry II, Georg-August-Universität Göttingen, Germany.',
 'Departments of Anatomy and Embryology and Anatomy and Cell Biology, Georg-August-University of Göttingen, Göttingen, Germany',
 'Historische Anthropologie und Humanökologie, Institut für Zoologie und Anthropologie, Georg August Universität Göttingen, Göttingen, Germany',
 'Forschungsgruppe Röntgenmikroskopie, Universität Göttingen, Geismarlandstraße 11, D-3400, Göttingen, Fed. Rep. of Germany',
 'Quality of Plant Products, Department of Crop Science, Faculty of Agricultural Science,Georg – August University Göttingen, 37075 Göttingen,Germany',
 'Institut für Physikalische Chemie der Universität Göttingen',
 'Institut für Physikalische Chemie der Universität, D-3400 Göttingen, West Germany',
 'Institut für Anorganische Chemie der Universität Göttingen, Tammannstrasse 4, 37077 Göttingen, Germany, and Theoretische and Computergestützte Biophysik, Max Planck Institut Göttingen, Am Fassberg 11, 37077 Göttingen, Germany',
 'Department of Animal Sciences, University of Göttingen, D-37075 Göttingen, Germany.',
 'Institut für Physikalische Chemie; Georg-August-Universität Göttingen; Tammannstraße 6 37077 Göttingen Germany',
 'Institut für Mikrobiologie der Georg-August-Universität zu Göttingen, Federal Republic of Germany.',
 'Institut für Anorganische Chemie, Georg‐August‐Universität Göttingen Tammannstr. 4, D‐37077 Göttingen, Germany',
 'Institut für Physikalische Chemie, Universität Göttingen, Tammannstr. 6,Göttingen,Germany',
 'Lehrstuhl für Betriebswirtschaftslehre, Universität Göttingen, Göttingen, Deutschland',
 'Department of Animal Sciences, Georg August University, Albrecht-Thaer-Weg 3, 37075 Göttingen, Germany.',
 'Inst. f. Organische Chemie, Georg‐August‐Universität, Tammannstr. 2, 37077 Göttingen, Germany',
 'Göttingen, Anorganisch‐Chemisches Institut der Universität',
 'Institut für Mathematische Statistik, Universität Göttingen, Bürgerstrasse 32, Germany',
 'Insitute of Human Genetics, University of Göttingen, Göttingen, Germany',
 'Institut für Technische Chemie, Technische Universität Clausthal, Erzstrasse 18, 38678 Clausthal-Zellerfeld, Germany, and Institut für Physikalische Chemie, Georg-August-Universität Göttingen, Tammannstrasse 6, 37077 Göttingen, Germany',
 'I. Physik. Institut, Georg-August Universität Göttingen, D-37077 Göttingen, Germany',
 'Department of Anatomy and Embryology, Georg-August University of Göttingen, Germany.',
 'Landscape Ecology Unit, Institute of Geography, University of Göttingen, Göttingen, Germany',
 'Göttingen Genomics Laboratory, Institut für Mikrobiologie und Genetik, Georg-August-Universität Göttingen, Grisebachstr. 8, D-37077 Göttingen, Germany',
 'Georg-Elias-Müller Institute of Psychology, University of Göttingen, Gosslerstr. 14, D-37073, Göttingen',
 'Georg-August-Universität Göttingen, Platz der Göttinger Sieben 5, 37073 Göttingen, Germany',
 'Mathematisches Institut der, Georg-August-Universität, Göttingen, Germany',
 'aInstitut für Astrophysik, Georg‐August‐Universität, D‐37077 Göttingen, Germany',
 'Center for Geosciences, University of Göttingen, Goldschmidtstr. 3, D-37077 Göttingen, Germany',
 'Lehrstuhl für Biochemie der Pflanze, Universität Göttingen, Untere Karspüle 2, 3400 Göttingen, Federal Republic of Germany.',
 'Department of Anatomy, University of Göttingen, Kreuzbergring 36, D-3400 Göttingen, F.R.G.',
 'Organisch-Chemisches Institut der Universität, Göttingen,',
 'Institut für Organische Chemie der Universität Göttingen, Tammanstraße 2, D‐37007 Göttingen',
 'III. Physikalisches Institut, Georg-August-Universität, 37077\xa0Göttingen, Germany',
 'Dept. of Forest Genetics and Forest Tree Breeding, University of Göttingen, Göttingen, Germany',
 'Nephrology, University of Göttingen, Göttingen',
 'Institute of Soil Science and Forest Nutrition, Georg‐August‐University Göttingen, Buesgenweg 2, D‐37770 Göttingen, Germany,',
 'Bioclimatology, Georg-August-Universität Göttingen, Göttingen, Germany',
 'Department of Psychosomatics and Psychotherapy, University of Göttingen, Germany',
 'Theoretical Chemistry Group, University of Göttingen, D-34 Göttingen, West Germany',
 'Anorganisch Chemischen Institut der Universität Göttingen, Deutschland',
 'a Drittes Physikalisches Institut, Universität Göttingen, 3400 Göttingen, Federal Republic Germany',
 'Georg August University Göttingen, Cologne',
 'Department of Ecosystem Modelling, Faculty of Forest Sciences and Forest Ecology, University of Goettingen, Goettingen, Germany',
 'University of Goettingen (Gottingen) - Ibero-America-Institute for Economic Research',
 'Institute of Human Genetics, University of Goettingen, D-37073 Goettingen, Germany',
 'Institut für Anorganische Chemie der Universität, Tammannstrasse 4, D‐3400 Göttingen (Germany)',
 'Plant Ecology, Albrecht von Haller Institute for Plant Sciences, Georg August University of Göttingen, Göttingen, Germany',
 'Institut für Anorganische Chemie der Universität Göttingen, Tammannstraße 4, D-3400 Göttingen B.R.D.',
 'Inst. Org. Chem., Georg‐August‐Univ., D‐37077 Goettingen, Germany',
 'Department of Bacteriology, Georg-August-Universität Göttingen, Kreuzbergring 57, D-37075 Göttingen, Germany',
 'Institute for Forest Genetics and Plant Breeding, University of Göttingen, Göttingen, Germany',
 'Georg-August-Universität GÖttingen, GÖttingen, Germany',
 'Institute for Nonlinear Dynamics, Georg–August–Universität Göttingen, 37077 Göttingen, Germany',
 'Dept. of Pediatrics, University of Göttingen, Germany',
 'Institute for Soils Science and Forest Nutrition, Georg-August-University, Buesgenweg 2, D-37077 Göttingen, Germany',
 "Institute of Psychology & Courant Research Centre, 'Evolution of Social Behaviour', University of Göttingen, Germany",
 'Department Silviculture & Forest Ecology of the Temperate Zones, University of Göttingen, Büsgenweg 1, 37077 Göttingen, Germany',
 'Agroecology\u2003, University of Göttingen, Waldweg 26, D-37073 Göttingen, Germany',
 'Department of Applied Geology, University of Göttingen, Goldschmidtstraße 3,  Göttingen D-37077, Germany',
 'II. Physikalisches Institut, Universität Göttingen, Göttingen, Germany',
 'II. Institute of Physics, University of Göttingen, Friedrich-Hund-PLatz 1, Gottingen, 37077, Germany',
 'Department of Pediatrics, University of Göttingen, Göttingen, Germany',
 'Universitäts-Sternwarte Göttingen',
 'Georg August University, Goettingen, Germany',
 'Department of Obstetrics and Gynecology and Department of Pediatrics, University of Göttingen, Göttingen',
 'Universität Göttingen, Thorax-, Herz- und Gefäßchirurgie, Göttingen, Germany',
 'Inst. Anorg. Chem., Univ., W‐3400 Goettingen, Fed. Rep. Ger.',
 'Telematics Group, University of Goettingen, Lotzestrasse 16-18, D-37083 Goettingen, Germany',
 'Abteilung Anatomie und Embryologie, Georg-August-Universität zu Göttingen, Kreuzbergring 36, 37075 Göttingen, Germany.',
 'Johann Friedrich Blumenbach Institute of Zoology and Anthropology, University of Göttingen, Göttingen, Germany',
 'Organisch‐Chemisches Institut der Universität, 34 Göttingen, Windausweg 2',
 'Institut für Anorganische Chemie der Universität, Tammannstraße 4, D ‐ 3400 Göttingen',
 'Im Siebigsfeld 17, Duderstadt, D‐37115, Germany E-mail: kbest@gwdg.de',
 'Institute of Zoology and Anthropology, University of Goettingen, Berliner Str. 28, D‐37073 Goettingen, Germany',
 'Abteilung für Biophysik / komplexe Systeme, Drittes Physikalis-ches Institut, Georg-August Universität Göttingen Weitere Mitglieder der Prüfungskomission',
 'IV. Phys. Inst., Univ. Gottingen, Gottingen, West Germany',
 'II. Physikalisches Institut, Universität Göttingen, Bunsenstrasse 7–9, D-37073\u2009Göttingen, Germany',
 'University of Goettingen (Gottingen) - Faculty of Economics and Business Administration',
 'University of Göttingen, Germany',
 'Department for Plant Biochemistry, Albrecht‐von‐Haller‐Institute for Plant Sciences, Georg‐August‐University, Justus‐von‐Liebig Weg 11, 37077 Göttingen Fax: +49 551/39‐5749.',
 'Georg-August University Göttingen, Germany',
 'Department of Pediatrics, University of Göttingen, Humboldtallee 23, 37073 Göttingen, Germany',
 'Institute of Anthropology, University of Göttingen, Göttingen, Germany.',
 'Georg-August University of Göttingen',
 'Institut für Anorganische Chemie, Georg-August-Universität, Tammannstraße 4, 37077 Göttingen, Germany',
 'der Georg-August-Universität zu Göttingen vorgelegt von .',
 'Universitäts-Sternwarte, Geismarlandstraße 11, D-37083, Göttingen, Germany',
 'University of Goettingen (Gottingen) - School of Law, Economics, Social Sciences',
 'Albrecht von Haller Institute of Plant Sciences, University of Göttingen, Untere Karspüle 2, D-37073 Göttingen, Germany',
 'II. Physik Institut, Universität Göttingen, D-Göttingen, Germany',
 'Institut für Physikalische Chemie, Universität Göttingen, Tammannstraße 6, D−37077 Göttingen, Germany',
 'Agroecology, Georg — August University, Göttingen, Germany',
 'Mathematisch-Naturwissenschaftlichen Fakultäten der Georg-August-Universität zu Göttingen vorgelegt von',
 'Chemisches Institut der Universität Göttingen.',
 'Abteilung Histologie, Zentrum Anatomie, Universität Göttingen, Kreuzbering 36, 37075 Göttingen, Germany',
 'GZG Abt. Kristallographie, Georg-August-Universität Göttingen, Goldschmidtstrasse 1, 37077\u2009Göttingen, Germany',
 'II. Physikalisches Institut, Universität Göttingen, D-37073 Göttingen, Germany',
 'Plant Biochemistry, Albrecht-von-Haller-Institute for Plant Sciences, Georg-August-University Göttingen, D-37077 Göttingen, Germany',
 'Institut für Anorganische Chemie, Georg-August-Universität, Tammannstr. 4, 37077 Göttingen',
 'Universitäts–Sternwarte, Göttingen, Germany',
 'Mathematisches Institut, Universität Göttingen, Deutschland',
 'Drittes physikalisches Inst. , Universität Göttingen , Bürgerstr. 42, D 34 Göttingen, Germany',
 'Institut für Physikalische Chemie, Georg-August-Universität Göttingen, Tammannstrasse 6, D-37077 Göttingen, Germany',
 'Institut für Organische Chemie, Georg‐August‐Universität Göttingen Tammannstrasse 2, 37077 Göttingen, Germany',
 'Institut für Anorganische Chemie der Universität Göttingen, Tammannstraße 4, D‐3400 Göttingen',
 'Göttingen, Anorganisch‐chemisches Institut der Universität',
 'Institute of Microbiology and Genetics, Georg August University, Göttingen, Germany',
 'Institut für Organische Chemie der Universität Göttingen, Tammannstraße 2, D‐37077 Göttingen, Germany Fax: (internat.) + 49(0)551/399476',
 'Organisch-Chemisches Institut der Universität Göttingen, Tammannstraße 2, D-3400 Göttingen',
 'Institut für Astrophysik, Universität Göttingen, Germany',
 'Georg-August-University = Georg-August-Universität Göttingen',
 'Institute of Marketing and Retailing, Georg-August-Universität Göttingen, Germany',
 'II. Phys. Institut, Universität Göttingen, Bunsenstr. 7-9, D-37073 Göttingen, Germany',
 'Geochemisches Institut der Universität, Goldschmidtstrasse 1, 3400, Göttingen, Germany',
 'Organisch-Chemischen Institut der Universität Göttingen',
 'Department of Structural Chemistry, Göttingen University, Tammannstrasse 4, D-37077 Göttingen, Germany.',
 'Department of Pediatrics, University of Gottingen, Gottingen, Federal Republic of Germany',
 'University of Göttingen, Göttingen Germany',
 'II. Physikalisches Institut und SFB 345, Universität Göttingen, Bunsenstrasse 7, 37073 Göttingen, Germany',
 'Institute of Organic Chemistry of the Georg-August-Universität Göttingen, Tammannstrasse 2, D-37077 Göttingen (Germany), Fax: (+49)\u2009551–389476',
 'Georg August University of Göttingen, Department of Crop Sciences, Grisebachstr. 6, 37077 Göttingen, Germany',
 'Department of Plant Ecology, Albrecht von Haller Institute of Plant Sciences, University of Göttingen, Untere Karspüle 2, 37073 Göttingen, Germany.',
 'Isotopenlaboratorium der Georg-August-Universita¨t Go¨ttingen, Burckhardtweg 2, 3400 Go¨ttingen, F.R.G.',
 'II Physikalisches Institut, Universität Göttingen, Friedrich-Hund-Platz 1, 37077 Göttingen, Germany',
 'Plant Ecology, Albrecht-von-Haller-Institute of Plant Sciences, University of Göttingen, 37073 Göttingen, Germany',
 'Department of Biochemistry II, Georg August University of Göttingen, Heinrich-Düker-Weg 12, 37073 Göttingen, Germany, the',
 'Angewandte Geologie, Universität Göttingen, Goldschmidtstraße 3, D-37077 Göttingen, Germany',
 'Organisch-chemisches Institut der Universität Göttingen, Göttingen, Deutschland',
 'Georg-August Universität Göttingen, Tammannstrasse 4, 37077 Göttingen, Germany',
 'University of Göttingen, Institute of Microbiology and Genetics, Department of Bioinformatics, Goldschmidtstr. 1, 37077 Göttingen, Germany#TAB#',
 'Abteilung Biochemie II, Zentrum Biochemie und Molekulare Zellbiologie, Georg-August-Universität Göttingen, Germany.',
 'Institut für Theoretische Physik, Universität Göttingen, Germany',
 'Courant Research Centre “Evolution of Social Behaviour”, Georg‐August‐University Göttingen, Göttingen, Germany',
 'b    German Government at the Seminar für Politikwissenschaft, Georg-August-Universität, Göttingen',
 'Anorganisch-Chemisches Institut der Universität Göttingen, Tammannstraße 4, D-3400 Göttingen West Germany',
 'Drittes Physikalisches Institut, Universität Göttingen, Bürgerstr. 42-44, D-3400 Göttingen 1, Federal Republic of Germany',
 'Institute of Soil Science and Forest Nutrition, University of Göttingen, Büsgenweg 2,\u200337077 Göttingen, Germany,',
 'Prosthodontics, Georg August University, Göttingen, Germany',
 'Plant Ecology, Albrecht-von-Haller Institute for Plant Sciences, University of Göttingen, Goettingen, Germany',
 'Institute of Human Genetics, University of Göttingen, Gosslerstrasse 12d, D-3400 Göttingen, FRG',
 'Institut für Anorganische Chemie der Universität Göttingen, Tammannstrasse 4, D-37077 Göttingen, Germany',
 'Universitätssternwarte, Göttingen, Germany',
 'Univ. Göttingen, Inst. für Theoretische Physik, Friedreich-Hund-Platz 1, D-37077 Göttingen, Germany',
 'Forstbotanisches Institut, Universität Göttingen, D-3400 Göttingen, Germany',
 'Institut für Materialphysik, Georg-August-Universität Göttingen, 37077 Göttingen, Germany',
 'Institut für Organische Chemie der Universität Tammannstraße 2, D-3400 Göttingen',
 'Institute of Infectology, Federal Research Institute for Animal Health, Friedrich-Loeffler-Institut, Südufer 10, 17493 Greifswald-Insel Riems, Germany. sohleme@gwdg.de',
 'University of Goettingen, Goettingen, Germany',
 'der Fakultät für Agrarwissenschaften der Georg-August-Universität Göttingen vorgelegt von',
 'Department of Biochemistry II, University of Göttingen, Göttingen, Germany',