In [41]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from bs4 import BeautifulSoup
import pandas as pd

In [48]:
dfg_ids = [
    {
        'name': 'Carl von Ossietzky Universität Oldenburg',
        'dfg_id': 10233, 
    },
    {
        'name': 'Hochschule für Musik, Theater und Medien Hannover',
        'dfg_id': 10246, 
    },
    {
        'name': 'Jade Hochschule Wilhelmshaven/Oldenburg/Elsfleth',
        'dfg_id': 10533, 
    },
    {
        'name': 'Universität Osnabrück',
        'dfg_id': 10244, 
    },
    {
        'name': 'Ostfalia Hochschule für angewandte Wissenschaften',
        'dfg_id': 10254, 
    },
    {
        'name': 'Gottfried Wilhelm Leibniz Universität Hannover',
        'dfg_id': 10238, 
    },
    {
        'name': 'Hochschule Hannover',
        'dfg_id': 10252, 
    },
    {
        'name': 'Medizinische Hochschule Hannover (MHH)',
        'dfg_id': 10247, 
    },
    {
        'name': 'Georg-August-Universität Göttingen',
        'dfg_id': 10236, 
    },
    {
        'name': 'Technische Universität Braunschweig',
        'dfg_id': 10240, 
    },
    {
        'name': 'Hochschule Emden/Leer',
        'dfg_id': 980710, 
    },
    {
        'name': 'Stiftung Universität Hildesheim',
        'dfg_id': 10235, 
    },
    {
        'name': 'Stiftung Tierärztliche Hochschule Hannover',
        'dfg_id': 10249, 
    },
    {
        'name': 'Technische Universität Clausthal',
        'dfg_id': 10242, 
    },
    {
        'name': 'Hochschule Osnabrück',
        'dfg_id': 10255, 
    },
    {
        'name': 'Hochschule für Bildende Künste Braunschweig',
        'dfg_id': 10251, 
    },
    {
        'name': 'Universität Vechta',
        'dfg_id': 10597, 
    },
    {
        'name': 'Leuphana Universität Lüneburg',
        'dfg_id': 10232, 
    },
    {
        'name': 'HAWK Hochschule für angewandte Wissenschaft und Kunst',
        'dfg_id': 10253, 
    },
]

In [66]:
driver = webdriver.Firefox()
driver.get('https://gerit.org/de/institutiondetail/10236')

button = WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.CSS_SELECTOR, '#associatedData span'))
)

# manchmal taucht ein cookie banner auf
driver.execute_script('arguments[0].click();', button)

element = WebDriverWait(driver, 10).until(
    EC.presence_of_element_located((By.ID, 'associated'))
)

content = driver.page_source
driver.quit()

In [67]:
soup = BeautifulSoup(content, features='html.parser')

In [68]:
list_of_institutions = soup.find(name='div', attrs={'id': 'associated'})

In [69]:
li = list_of_institutions.find_all(name='li')

In [132]:
for inst in li:
    list_of_spans = inst.find_all('span')
    #print(inst.find('span').text + ': ' + inst.find('a', href=True).get('href').replace('/de/institutiondetail/', '') + ' ' + (inst.find('div').get('class')[-1]))
    list_of_subs = inst.find_all(name='span', attrs={'class': 'associated-institution'})
    print(list_of_subs[0].text + ' ' + inst.find('div').get('class')[-1] + ': ' + inst.find('a', href=True).get('href').replace('/de/institutiondetail/', ''))
    print('#####')
    for i, subs in enumerate(list_of_subs):
        if i == 0:
            pass
        else:
            print(subs.text + ' ' + inst.find('div').get('class')[0])
    print('----------------')

Campus Institut für Dynamik biologischer Netzwerke (CIDBN) level0: 443884006
#####
Abteilung Datengetriebene Analyse biologischer Netzwerke associated-contend
----------------
Abteilung Datengetriebene Analyse biologischer Netzwerke level1: 443885740
#####
----------------
Campus-Institut Data Science (CIDAS) level0: 565050847
#####
----------------
Centre for Modern Indian Studies (CeMIS) level0: 179419375
#####
Forschungsgruppe Moderne Indische Geschichte associated-contend
----------------
Forschungsgruppe Moderne Indische Geschichte level1: 517973470
#####
----------------
Courant Forschungszentrum "Armut, Ungleichheit und Wachstum in Entwicklungsländern" level0: 232350829
#####
----------------
Courant Forschungszentrum "Bildung und Religion" level0: 214341364
#####
Area 1: Pietas und Paideia. Religiöse Traditionen und intellektuelle Kulturen in der Welt des Römischen Reiches associated-contend
----------------
Area 1: Pietas und Paideia. Religiöse Traditionen und intellektuelle Kulturen in der Welt des Römischen Reiches level1: 252506619
#####
----------------
Courant Forschungszentrum "Evolution des Sozialverhaltens" level0: 171578186
#####
----------------
Courant Forschungszentrum "Nanospektroskopie und Röntgenbildgebung" level0: 102731477
#####
----------------
Courant Forschungszentrum Geobiologie level0: 236737778
#####
----------------
Courant-Forschungszentrum "Textstrukturen" level0: 203731822
#####
----------------
DFG Forschungszentrum für Molekularphysiologie des Gehirns level0: 13204649
#####
----------------
Erasmus Mundus Programme Euroculture - Society, politics and culture in a global context level0: 325190424
#####
----------------
Fakultät für Agrarwissenschaften level0: 13696
#####
Außenstelle Vechta associated-contend
Department für Agrarökonomie und Rurale Entwicklung associated-contend
Abteilung Management der Agrar- und Ernährungswirtschaft associated-contend
Abteilung Umwelt- und Ressourcenökonomik associated-contend
Lehrstuhl Ökonomik nachhaltiger Agrar- und Ernährungssysteme associated-contend
Arbeitsbereich Welternährungswirtschaft und rurale Entwicklung associated-contend
Fachgebiet Sozial-ökologische Interaktionen in Agrarsystemen associated-contend
Forschungsverbund Zukunft der Ernährung in Niedersachsen (ZERN) associated-contend
Lehrstuhl Betriebswirtschaftslehre des Agribusiness associated-contend
Lehrstuhl für Agrarpolitik associated-contend
Lehrstuhl für Landwirtschaftliche Betriebslehre associated-contend
Lehrstuhl für Landwirtschaftliche Marktlehre associated-contend
Lehrstuhl für Soziologie Ländlicher Räume associated-contend
Lehrstuhl Marketing für Lebensmittel und Agrarprodukte associated-contend
Department für Nutzpflanzenwissenschaften associated-contend
Abteilung Agrarpedologie associated-contend
Abteilung Agrartechnik associated-contend
Abteilung Agrarökologie und Funktionelle Agrobiodiversität associated-contend
Abteilung Biogeochemie der Agrarökosysteme associated-contend
Abteilung Bodenhydrologie associated-contend
Abteilung Bodenphysik associated-contend
Abteilung Graslandwissenschaft associated-contend
Abteilung Nutzpflanzengenetik associated-contend
Abteilung Pflanzenbau associated-contend
Abteilung Pflanzenernährung und Ertragsphysiologie associated-contend
Abteilung Qualität pflanzlicher Erzeugnisse associated-contend
Abteilung Qualität und Sensorik pflanzlicher Erzeugnisse associated-contend
Abteilung Tropischer Pflanzenbau und Agrosystem Modellierung associated-contend
Abteilung Zuchtmethodik der Pflanze associated-contend
Fachgebiet Pflanzenpathologie und Pflanzenschutz associated-contend
Abteilung Agrarentomologie associated-contend
Abteilung Molekulare Phytopathologie und Mykotoxinforschung associated-contend
Department Nutztierwissenschaften associated-contend
Abteilung Aquakultur und Gewässerökologie associated-contend
Abteilung Biotechnologie und Reproduktion landwirtschaftlicher Nutztiere associated-contend
Abteilung Functional Breeding associated-contend
Abteilung für Systeme der Nutztierhaltung associated-contend
Abteilung Mikrobiologie und Tierhygiene associated-contend
Abteilung Tierernährungsphysiologie und Ressourceneffizienz associated-contend
Lehrstuhl für Tierernährungslehre associated-contend
Abteilung Tierzucht und Haustiergenetik associated-contend
Abteilung Wiederkäuerernährung associated-contend
Abteilung Ökologie der Nutztierhaltung associated-contend
Arbeitsgruppe Biometrie und Bioinformatik associated-contend
Arbeitsgruppe Produktqualität tierischer Erzeugnisse associated-contend
Arbeitsgruppe Tierhaltung in den Tropen und Subtropen associated-contend
Tierärztliches Institut associated-contend
Institut für angewandte Pflanzenernährung (IAPN) associated-contend
----------------
Außenstelle Vechta level1: 157085139
#####
----------------
Department für Agrarökonomie und Rurale Entwicklung level1: 16802
#####
Abteilung Management der Agrar- und Ernährungswirtschaft associated-contend
Abteilung Umwelt- und Ressourcenökonomik associated-contend
Lehrstuhl Ökonomik nachhaltiger Agrar- und Ernährungssysteme associated-contend
Arbeitsbereich Welternährungswirtschaft und rurale Entwicklung associated-contend
Fachgebiet Sozial-ökologische Interaktionen in Agrarsystemen associated-contend
Forschungsverbund Zukunft der Ernährung in Niedersachsen (ZERN) associated-contend
Lehrstuhl Betriebswirtschaftslehre des Agribusiness associated-contend
Lehrstuhl für Agrarpolitik associated-contend
Lehrstuhl für Landwirtschaftliche Betriebslehre associated-contend
Lehrstuhl für Landwirtschaftliche Marktlehre associated-contend
Lehrstuhl für Soziologie Ländlicher Räume associated-contend
Lehrstuhl Marketing für Lebensmittel und Agrarprodukte associated-contend
----------------
Abteilung Management der Agrar- und Ernährungswirtschaft level2: 506591444
#####
----------------
Abteilung Umwelt- und Ressourcenökonomik level2: 25977
#####
Lehrstuhl Ökonomik nachhaltiger Agrar- und Ernährungssysteme associated-contend
----------------
Lehrstuhl Ökonomik nachhaltiger Agrar- und Ernährungssysteme level3: 551171859
#####
----------------
Arbeitsbereich Welternährungswirtschaft und rurale Entwicklung level2: 16809
#####
----------------
Fachgebiet Sozial-ökologische Interaktionen in Agrarsystemen level2: 407252766
#####
----------------
Forschungsverbund Zukunft der Ernährung in Niedersachsen (ZERN) level2: 563520382
#####
----------------
Lehrstuhl Betriebswirtschaftslehre des Agribusiness level2: 210302701
#####
----------------
Lehrstuhl für Agrarpolitik level2: 25954
#####
----------------
Lehrstuhl für Landwirtschaftliche Betriebslehre level2: 25959
#####
----------------
Lehrstuhl für Landwirtschaftliche Marktlehre level2: 28104
#####
----------------
Lehrstuhl für Soziologie Ländlicher Räume level2: 210303221
#####
----------------
Lehrstuhl Marketing für Lebensmittel und Agrarprodukte level2: 29672592
#####
----------------
Department für Nutzpflanzenwissenschaften level1: 16806
#####
Abteilung Agrarpedologie associated-contend
Abteilung Agrartechnik associated-contend
Abteilung Agrarökologie und Funktionelle Agrobiodiversität associated-contend
Abteilung Biogeochemie der Agrarökosysteme associated-contend
Abteilung Bodenhydrologie associated-contend
Abteilung Bodenphysik associated-contend
Abteilung Graslandwissenschaft associated-contend
Abteilung Nutzpflanzengenetik associated-contend
Abteilung Pflanzenbau associated-contend
Abteilung Pflanzenernährung und Ertragsphysiologie associated-contend
Abteilung Qualität pflanzlicher Erzeugnisse associated-contend
Abteilung Qualität und Sensorik pflanzlicher Erzeugnisse associated-contend
Abteilung Tropischer Pflanzenbau und Agrosystem Modellierung associated-contend
Abteilung Zuchtmethodik der Pflanze associated-contend
Fachgebiet Pflanzenpathologie und Pflanzenschutz associated-contend
Abteilung Agrarentomologie associated-contend
Abteilung Molekulare Phytopathologie und Mykotoxinforschung associated-contend
----------------
Abteilung Agrarpedologie level2: 16805
#####
----------------
Abteilung Agrartechnik level2: 16803
#####
----------------
Abteilung Agrarökologie und Funktionelle Agrobiodiversität level2: 25827
#####
----------------
Abteilung Biogeochemie der Agrarökosysteme level2: 452408258
#####
----------------
Abteilung Bodenhydrologie level2: 236843247
#####
----------------
Abteilung Bodenphysik level2: 516324464
#####
----------------
Abteilung Graslandwissenschaft level2: 25979
#####
----------------
Abteilung Nutzpflanzengenetik level2: 437118740
#####
----------------
Abteilung Pflanzenbau level2: 20687682
#####
----------------
Abteilung Pflanzenernährung und Ertragsphysiologie level2: 25985
#####
----------------
Abteilung Qualität pflanzlicher Erzeugnisse level2: 25986
#####
----------------
Abteilung Qualität und Sensorik pflanzlicher Erzeugnisse level2: 513979320
#####
----------------
Abteilung Tropischer Pflanzenbau und Agrosystem Modellierung level2: 16807
#####
----------------
Abteilung Zuchtmethodik der Pflanze level2: 437118994
#####
----------------
Fachgebiet Pflanzenpathologie und Pflanzenschutz level2: 16808
#####
Abteilung Agrarentomologie associated-contend
Abteilung Molekulare Phytopathologie und Mykotoxinforschung associated-contend
----------------
Abteilung Agrarentomologie level3: 25988
#####
----------------
Abteilung Molekulare Phytopathologie und Mykotoxinforschung level3: 100497857
#####
----------------
Department Nutztierwissenschaften level1: 157084871
#####
Abteilung Aquakultur und Gewässerökologie associated-contend
Abteilung Biotechnologie und Reproduktion landwirtschaftlicher Nutztiere associated-contend
Abteilung Functional Breeding associated-contend
Abteilung für Systeme der Nutztierhaltung associated-contend
Abteilung Mikrobiologie und Tierhygiene associated-contend
Abteilung Tierernährungsphysiologie und Ressourceneffizienz associated-contend
Lehrstuhl für Tierernährungslehre associated-contend
Abteilung Tierzucht und Haustiergenetik associated-contend
Abteilung Wiederkäuerernährung associated-contend
Abteilung Ökologie der Nutztierhaltung associated-contend
Arbeitsgruppe Biometrie und Bioinformatik associated-contend
Arbeitsgruppe Produktqualität tierischer Erzeugnisse associated-contend
Arbeitsgruppe Tierhaltung in den Tropen und Subtropen associated-contend
Tierärztliches Institut associated-contend
----------------
Abteilung Aquakultur und Gewässerökologie level2: 210324567
#####
----------------
Abteilung Biotechnologie und Reproduktion landwirtschaftlicher Nutztiere level2: 471756446
#####
----------------
Abteilung Functional Breeding level2: 356541912
#####
----------------
Abteilung für Systeme der Nutztierhaltung level2: 210325786
#####
----------------
Abteilung Mikrobiologie und Tierhygiene level2: 210324916
#####
----------------
Abteilung Tierernährungsphysiologie und Ressourceneffizienz level2: 283365652
#####
Lehrstuhl für Tierernährungslehre associated-contend
----------------
Lehrstuhl für Tierernährungslehre level3: 16810
#####
----------------
Abteilung Tierzucht und Haustiergenetik level2: 16811
#####
----------------
Abteilung Wiederkäuerernährung level2: 340649009
#####
----------------
Abteilung Ökologie der Nutztierhaltung level2: 210325326
#####
----------------
Arbeitsgruppe Biometrie und Bioinformatik level2: 266143724
#####
----------------
Arbeitsgruppe Produktqualität tierischer Erzeugnisse level2: 35306236
#####
----------------
Arbeitsgruppe Tierhaltung in den Tropen und Subtropen level2: 981014
#####
----------------
Tierärztliches Institut level2: 16812
#####
----------------
Institut für angewandte Pflanzenernährung (IAPN) level1: 445754280
#####
----------------
Fakultät für Biologie und Psychologie level0: 13697
#####
Albrecht-von-Haller-Institut für Pflanzenwissenschaften associated-contend
Abteilung Bioanalytik associated-contend
Abteilung Biochemie der Pflanze associated-contend
Abteilung Experimentelle Phykologie und Sammlung von Algenkulturen (EPSAG) associated-contend
Abteilung für die Didaktik der Biologie associated-contend
Abteilung Molekularbiologie und Physiologie der Pflanze associated-contend
Abteilung Molekulare Stressphysiologie der Pflanzen associated-contend
Abteilung Palynologie und Klimadynamik associated-contend
Abteilung Systematik, Biodiversität und Evolution der Planzen associated-contend
Abteilung Vegetationsanalyse und Phytodiversität associated-contend
Abteilung Zellbiologie der Pflanze associated-contend
Abteilung Ökologie und Ökosystemforschung associated-contend
Alter Botanischer Garten associated-contend
Experimenteller Botanischer Garten associated-contend
Nachwuchsgruppe Molekularbiologie der Pflanze-Mikroben-Interaktionen associated-contend
Georg-Elias-Müller-Institut für Psychologie associated-contend
Abteilung Affektive Neurowissenschaft und Psychophysiologie associated-contend
Abteilung Biologische Persönlichkeitspsychologie associated-contend
Abteilung der Psychologie der Sprache associated-contend
Abteilung für Arbeits- und Organisationspsychologie associated-contend
Abteilung für Experimentelle Psychologie associated-contend
Abteilung für Klinische Psychologie und Psychotherapie associated-contend
Abteilung für Kognitionswissenschaft und Entscheidungspsychologie associated-contend
Abteilung für Kognitive Entwicklungspsychologie associated-contend
Abteilung für Pädagogische Psychologie associated-contend
Abteilung für Sozial- und Kommunikationspsychologie associated-contend
Abteilung für Wirtschafts- und Sozialpsychologie associated-contend
Abteilung Klinische Psychologie und Experimentelle Psychopathologie associated-contend
Abteilung Kognition, Emotion und Verhalten associated-contend
Abteilung Translationale Psychotherapie associated-contend
Institut für Mikrobiologie und Genetik associated-contend
Abteilung Angewandte Bioinformatik associated-contend
Abteilung für Allgemeine Mikrobiologie associated-contend
Abteilung für Bioinformatik associated-contend
Abteilung für Molekulare Mikrobiologie und Genetik associated-contend
Abteilung für Molekulare Strukturbiologie associated-contend
Göttinger Zentrum für Molekulare Biowissenschaften (GZMB) associated-contend
Institute for Molecular Oncology associated-contend
Abteilung Genetik eukaryotischer Mikroorganismen associated-contend
Abteilung Genomische und Angewandte Mikrobiologie associated-contend
Abteilung Molekulare Genetik associated-contend
Laboratorium für Genomanalyse associated-contend
Johann-Friedrich-Blumenbach Institut für Zoologie und Anthropologie associated-contend
Abteilung Biodiversität und Evolution der Tiere associated-contend
Abteilung Entwicklungsbiologie associated-contend
Abteilung Evolutionäre Entwicklungsgenetik associated-contend
Abteilung für molekulare Neurobiologie des Verhaltens associated-contend
Abteilung Historische Anthropologie und Humanökologie associated-contend
Abteilung Multiskalen-Biologie associated-contend
Abteilung Naturschutzbiologie associated-contend
Abteilung Soziobiologie/ Anthropologie associated-contend
Abteilung Systemische Neurobiologie associated-contend
Abteilung Verhaltensökologie associated-contend
Abteilung Zelluläre Neurobiologie associated-contend
Arbeitsgruppe Tierökologie associated-contend
----------------
Albrecht-von-Haller-Institut für Pflanzenwissenschaften level1: 16817
#####
Abteilung Bioanalytik associated-contend
Abteilung Biochemie der Pflanze associated-contend
Abteilung Experimentelle Phykologie und Sammlung von Algenkulturen (EPSAG) associated-contend
Abteilung für die Didaktik der Biologie associated-contend
Abteilung Molekularbiologie und Physiologie der Pflanze associated-contend
Abteilung Molekulare Stressphysiologie der Pflanzen associated-contend
Abteilung Palynologie und Klimadynamik associated-contend
Abteilung Systematik, Biodiversität und Evolution der Planzen associated-contend
Abteilung Vegetationsanalyse und Phytodiversität associated-contend
Abteilung Zellbiologie der Pflanze associated-contend
Abteilung Ökologie und Ökosystemforschung associated-contend
Alter Botanischer Garten associated-contend
Experimenteller Botanischer Garten associated-contend
Nachwuchsgruppe Molekularbiologie der Pflanze-Mikroben-Interaktionen associated-contend
----------------
Abteilung Bioanalytik level2: 209017176
#####
----------------
Abteilung Biochemie der Pflanze level2: 980946
#####
----------------
Abteilung Experimentelle Phykologie und Sammlung von Algenkulturen (EPSAG) level2: 23691
#####
----------------
Abteilung für die Didaktik der Biologie level2: 20781378
#####
----------------
Abteilung Molekularbiologie und Physiologie der Pflanze level2: 49046485
#####
----------------
Abteilung Molekulare Stressphysiologie der Pflanzen level2: 580899853
#####
----------------
Abteilung Palynologie und Klimadynamik level2: 23689
#####
----------------
Abteilung Systematik, Biodiversität und Evolution der Planzen level2: 23694
#####
----------------
Abteilung Vegetationsanalyse und Phytodiversität level2: 23695
#####
----------------
Abteilung Zellbiologie der Pflanze level2: 23693
#####
----------------
Abteilung Ökologie und Ökosystemforschung level2: 23692
#####
----------------
Alter Botanischer Garten level2: 20688190
#####
----------------
Experimenteller Botanischer Garten level2: 49066222
#####
----------------
Nachwuchsgruppe Molekularbiologie der Pflanze-Mikroben-Interaktionen level2: 172486634
#####
----------------
Georg-Elias-Müller-Institut für Psychologie level1: 16816
#####
Abteilung Affektive Neurowissenschaft und Psychophysiologie associated-contend
Abteilung Biologische Persönlichkeitspsychologie associated-contend
Abteilung der Psychologie der Sprache associated-contend
Abteilung für Arbeits- und Organisationspsychologie associated-contend
Abteilung für Experimentelle Psychologie associated-contend
Abteilung für Klinische Psychologie und Psychotherapie associated-contend
Abteilung für Kognitionswissenschaft und Entscheidungspsychologie associated-contend
Abteilung für Kognitive Entwicklungspsychologie associated-contend
Abteilung für Pädagogische Psychologie associated-contend
Abteilung für Sozial- und Kommunikationspsychologie associated-contend
Abteilung für Wirtschafts- und Sozialpsychologie associated-contend
Abteilung Klinische Psychologie und Experimentelle Psychopathologie associated-contend
Abteilung Kognition, Emotion und Verhalten associated-contend
Abteilung Translationale Psychotherapie associated-contend
----------------
Abteilung Affektive Neurowissenschaft und Psychophysiologie level2: 403605895
#####
----------------
Abteilung Biologische Persönlichkeitspsychologie level2: 27290
#####
----------------
Abteilung der Psychologie der Sprache level2: 560902828
#####
----------------
Abteilung für Arbeits- und Organisationspsychologie level2: 552189568
#####
----------------
Abteilung für Experimentelle Psychologie level2: 27289
#####
----------------
Abteilung für Klinische Psychologie und Psychotherapie level2: 27296
#####
----------------
Abteilung für Kognitionswissenschaft und Entscheidungspsychologie level2: 27288
#####
----------------
Abteilung für Kognitive Entwicklungspsychologie level2: 27292
#####
----------------
Abteilung für Pädagogische Psychologie level2: 49066395
#####
----------------
Abteilung für Sozial- und Kommunikationspsychologie level2: 27295
#####
----------------
Abteilung für Wirtschafts- und Sozialpsychologie level2: 27294
#####
----------------
Abteilung Klinische Psychologie und Experimentelle Psychopathologie level2: 540719621
#####
----------------
Abteilung Kognition, Emotion und Verhalten level2: 542876250
#####
----------------
Abteilung Translationale Psychotherapie level2: 534071898
#####
----------------
Institut für Mikrobiologie und Genetik level1: 16815
#####
Abteilung Angewandte Bioinformatik associated-contend
Abteilung für Allgemeine Mikrobiologie associated-contend
Abteilung für Bioinformatik associated-contend
Abteilung für Molekulare Mikrobiologie und Genetik associated-contend

In [56]:
df = pd.DataFrame.from_dict(dict(dfg_id=[], inst_name=[], level=[], parent_name=[], dfg_id_parent=[]))

for dfg_id_dict in dfg_ids:

    dfg_id = dfg_id_dict.get('dfg_id')
    parent_name = dfg_id_dict.get('name')
    
    driver = webdriver.Firefox()
    driver.get(f'https://gerit.org/de/institutiondetail/{dfg_id}')
    
    button = WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.CSS_SELECTOR, '#associatedData span'))
    )

    # manchmal taucht ein cookie banner auf
    driver.execute_script('arguments[0].click();', button)
    
    element = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.ID, 'associated'))
    )
    
    content = driver.page_source
    driver.quit()

    soup = BeautifulSoup(content, features='html.parser')
    list_of_institutions = soup.find(name='div', attrs={'id': 'associated'})
    li = list_of_institutions.find_all(name='li')

    inst_dict = dict(
        dfg_id = [],
        inst_name = [],
        level = [],
        parent_name = [],
        dfg_id_parent = []
    )

    for inst in li:
        inst_dict['dfg_id'].append(inst.find('a', href=True).get('href').replace('/de/institutiondetail/', ''))
        inst_dict['level'].append(inst.find('div').get('class')[-1])
        inst_dict['inst_name'].append(inst.find('span').text)
        inst_dict['parent_name'].append(parent_name)
        inst_dict['dfg_id_parent'].append(dfg_id)

    df2 = pd.DataFrame.from_dict(inst_dict)

    df = pd.concat([df, df2], ignore_index=True)

    df['dfg_id'] = df['dfg_id'].astype(int)
    df['dfg_id_parent'] = df['dfg_id_parent'].astype(int)

In [57]:
df

,dfg_id,inst_name,level,parent_name,dfg_id_parent
0,14332,Bibliotheks- und Informationssystem (BIS),level0,Carl von Ossietzky Universität Oldenburg,10233
1,14349,Center für lebenslanges Lernen (C3L),level0,Carl von Ossietzky Universität Oldenburg,10233
2,19052,"CMC - Center for Migration, Education and Cult...",level0,Carl von Ossietzky Universität Oldenburg,10233
3,35245680,COAST - Zentrum für Umwelt- und Nachhaltigkeit...,level0,Carl von Ossietzky Universität Oldenburg,10233
4,25628,ecco-ecology + communication Unternehmensberat...,level0,Carl von Ossietzky Universität Oldenburg,10233
...,...,...,...,...,...
2075,9409718,Fakultät Gestaltung,level1,HAWK Hochschule für angewandte Wissenschaft un...,10253
2076,21419305,Fakultät soziale Arbeit und Gesundheit,level1,HAWK Hochschule für angewandte Wissenschaft un...,10253
2077,277626399,"Studiengang MSc Ergotherapie, Logopädie, Physi...",level2,HAWK Hochschule für angewandte Wissenschaft un...,10253
2078,133037425,Standort Holzminden,level0,HAWK Hochschule für angewandte Wissenschaft un...,10253
2079,234812895,"Fakultät Management, Soziale Arbeit, Bauen",level1,HAWK Hochschule für angewandte Wissenschaft un...,10253

In [58]:
df.to_csv('../data/gerit_inst_with_ids.csv', index=False)

In [87]:
df[df.dfg_id_parent == 10236].head(20)

,dfg_id,inst_name,level,parent_name,dfg_id_parent
909,443884006,Campus Institut für Dynamik biologischer Netzw...,level0,Georg-August-Universität Göttingen,10236
910,443885740,Abteilung Datengetriebene Analyse biologischer...,level1,Georg-August-Universität Göttingen,10236
911,565050847,Campus-Institut Data Science (CIDAS),level0,Georg-August-Universität Göttingen,10236
912,179419375,Centre for Modern Indian Studies (CeMIS),level0,Georg-August-Universität Göttingen,10236
913,517973470,Forschungsgruppe Moderne Indische Geschichte,level1,Georg-August-Universität Göttingen,10236
914,232350829,"Courant Forschungszentrum ""Armut, Ungleichheit...",level0,Georg-August-Universität Göttingen,10236
915,214341364,"Courant Forschungszentrum ""Bildung und Religion""",level0,Georg-August-Universität Göttingen,10236
916,252506619,Area 1: Pietas und Paideia. Religiöse Traditio...,level1,Georg-August-Universität Göttingen,10236
917,171578186,"Courant Forschungszentrum ""Evolution des Sozia...",level0,Georg-August-Universität Göttingen,10236
918,102731477,"Courant Forschungszentrum ""Nanospektroskopie u...",level0,Georg-August-Universität Göttingen,10236
919,236737778,Courant Forschungszentrum Geobiologie,level0,Georg-August-Universität Göttingen,10236
920,203731822,"Courant-Forschungszentrum ""Textstrukturen""",level0,Georg-August-Universität Göttingen,10236
921,13204649,DFG Forschungszentrum für Molekularphysiologie...,level0,Georg-August-Universität Göttingen,10236
922,325190424,Erasmus Mundus Programme Euroculture - Society...,level0,Georg-August-Universität Göttingen,10236
923,13696,Fakultät für Agrarwissenschaften,level0,Georg-August-Universität Göttingen,10236
924,157085139,Außenstelle Vechta,level1,Georg-August-Universität Göttingen,10236
925,16802,Department für Agrarökonomie und Rurale Entwic...,level1,Georg-August-Universität Göttingen,10236
926,506591444,Abteilung Management der Agrar- und Ernährungs...,level2,Georg-August-Universität Göttingen,10236
927,25977,Abteilung Umwelt- und Ressourcenökonomik,level2,Georg-August-Universität Göttingen,10236
928,551171859,Lehrstuhl Ökonomik nachhaltiger Agrar- und Ern...,level3,Georg-August-Universität Göttingen,10236